version: "3.3"
services:
  mysql-server:
    container_name: mysql-wedding-auth
    image: "mysql:8.0.20"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./tmp/mysql-data:/var/lib/mysql
      - ./mysql-config:/docker-entrypoint-initdb.d
    networks:
      - WEDDING_NETWORK
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

  wedding-auth-server:
    container_name: wedding-auth-server
    restart: unless-stopped
    image: docker.pkg.github.com/kamranghiasvand/authentication-server/authentication-server
    environment:
      SERVER_PORT: 8081
    depends_on:
      - mysql-server
    volumes:
      - ./auth-server:/app/config
    networks:
      - WEDDING_NETWORK
    command: "\
    --logging.level.root=info \
    --spring.datasource.hikari.initializationFailTimeout=15000 \
    --spring.datasource.url=jdbc:mysql://mysql-server:3306/auth_server_prod?useUnicode=true&characterEncoding=UTF-8"
    ports:
      - "8081:8081"

networks:
  WEDDING_NETWORK:
    driver: bridge

